url = []
content_regex = "src=[\"'](http[s]?://[a-zA-Z0-9/._-]+(?::[0-9]+)?/[a-zA-Z0-9/._-]*[.](?:jpg|gif|png))(?:[?&#].*)?[\"']"
title_regex = "(?:\\<title\\>)(.*)(?:<\\/title\\>)"
path = ""
host = ""
allowed_origins = ["http://localhost:3000"]
