on: push
name: Test and Lint

jobs:
  test-and-lint:
    strategy:
      matrix:
        go-version: [1.16.x]
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@latest

      - uses: actions/checkout@v2
      - name: Generate
        run: go generate ./...

      - name: Test
        run: go test ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.47.3
          skip-pkg-cache: true
          skip-build-cache: true
